In [ ]:
#Comprehension e Expressões Geradoras

In [1]:
#Produto cartesiano de duas listas através de list comprehension aninhada
"""Objetivo: Gerar todas as combinações possíveis de camisetadas disponíveis dada uma lista de possíveis 
tamanhos e outra de cores
"""
cores = ["Preta", "Branca"]
tamanhos = ["P", "M", "G"]

[(cor, tamanho) for cor in cores 
                for tamanho in tamanhos]

[('Preta', 'P'),
 ('Preta', 'M'),
 ('Preta', 'G'),
 ('Branca', 'P'),
 ('Branca', 'M'),
 ('Branca', 'G')]

In [2]:
#Usando expressões geradoras para preencher uma tupla e um array.array
symbols = "#@?*"

In [3]:
tuple(ord(symbol) for symbol in symbols)

(35, 64, 63, 42)

In [4]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [35, 64, 63, 42])

In [6]:
#Produto cartesiano em uma expressão geradora
"""
Uma expressão geradora somente retorna o item, sem armazenálo na memória. 
Portanto ela pode ser usada para economizar memória, como abaixo:
"""

for camisa in ((cor, tamanho) for cor in cores for tamanho in tamanhos):
    print(*camisa)

Preta P
Preta M
Preta G
Branca P
Branca M
Branca G


In [7]:
#Tuplas
"""Pelo fato das tuplas serem imutáveis e seu tamanho poder ser fixo,
podemos dar um significado próprio para cada posição, como abaixo: """
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '3114521'), ('BRA', 'CE61842'), ('ESP', 'XDA98147')]

In [8]:
for passport in traveler_ids:
    print("%s/%s" % passport)
for country, _ in traveler_ids:
    print(country)

USA/3114521
BRA/CE61842
ESP/XDA98147
USA
BRA
ESP


In [9]:
#Utilidades de '*'
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [10]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [11]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [12]:
a, *body, b, c = range(5)
a, body, b, c

(0, [1, 2], 3, 4)

In [13]:
*head, a, b = range(5)
head, a, b

([0, 1, 2], 3, 4)

In [14]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]

In [15]:
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

                |   lat.    |   long.  


In [16]:
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

Mexico City     |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [17]:
#Tuplas Nomeadas
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691677))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691677))

In [18]:
tokyo.population

36.933

In [19]:
tokyo.coordinates

(35.689722, 139.691677)

In [20]:
tokyo[1]

'JP'

In [21]:
#Atributos importantes
City._fields

('name', 'country', 'population', 'coordinates')

In [22]:
Latlong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, Latlong(28.8124, 32.798182))
#permite instanciar uma tupla nomeada através de um iterável
delhi = City._make(delhi_data)
#retorna collections.OrderedDict, usado para melhorar a legibilidade do objeto
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.8124, long=32.798182)}

In [23]:
for key, value in delhi._asdict().items():
    print('{0}: {1}'.format(key, value))

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.8124, long=32.798182)


In [24]:
#Fatiamento
cod = slice(0,5)
nome = slice(5,24)
pais = slice(24,None)

items = """
1111 Saulo              Brasil        
2222 Roberto            Holanda       
3333 Carolina           Egito         
"""
for item in items.split('\n')[1:-1]:
    print(item[cod], item[nome], item[pais])

1111  Saulo               Brasil        
2222  Roberto             Holanda       
3333  Carolina            Egito         


In [25]:
#Fatiamento Multidimensional
import numpy as np

arr =np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
arr[1:, 1:]

array([[5, 6],
       [8, 9]])

In [26]:
arr[..., 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [27]:
#Atribuição de Valores a Fatias
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
l[2:5] = [20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [29]:
del(l[5:7])
l

[0, 1, 20, 30, 5, 8, 9]

In [30]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [31]:
#o valor de atribuição precisa ser um iterável
l[2:5] = 100

TypeError: can only assign an iterable

In [32]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [33]:
#Criando listas de listas
sala = [['_'] * 3 for _ in range(3)]
sala

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [34]:
sala[1][1] = 'X'
sala

[['_', '_', '_'], ['_', 'X', '_'], ['_', '_', '_']]

In [35]:
#Modo errado
sala_errado = [['_'] * 3] * 3
sala_errado

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [36]:
sala_errado[1][2] = 'X'
sala_errado

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [37]:
#Ordenação

In [38]:
frutas = ['banana', 'maçã', 'uva', 'melância', 'framboesa']
sorted(frutas)

['banana', 'framboesa', 'maçã', 'melância', 'uva']

In [39]:
sorted(frutas, reverse=True)

['uva', 'melância', 'maçã', 'framboesa', 'banana']

In [40]:
sorted(frutas, key=len)

['uva', 'maçã', 'banana', 'melância', 'framboesa']

In [41]:
sorted(frutas, key=len, reverse=True)

['framboesa', 'melância', 'banana', 'maçã', 'uva']

In [42]:
frutas

['banana', 'maçã', 'uva', 'melância', 'framboesa']

In [43]:
frutas.sort()

In [44]:
frutas

['banana', 'framboesa', 'maçã', 'melância', 'uva']

In [45]:
#bisect
import bisect
import sys

In [46]:
entrada = input()

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 26, 29, 30]
NEEDLES = [8, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d} {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * ' |'
        print(ROW_FMT.format(needle, position, offset))

if entrada == 'left':
    bisect_fn = bisect.bisect_left
else:
    bisect_fn = bisect.bisect

print('DEMO: ', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

3 4 6 1 2 5
DEMO:  bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 26 29 30
31 @ 13  | | | | | | | | | | | | |31
30 @ 13  | | | | | | | | | | | | |30
29 @ 12  | | | | | | | | | | | |29
23 @ 10  | | | | | | | | | |23
22 @  9  | | | | | | | | |22
10 @  5  | | | | |10
 8 @  5  | | | | |8 
 5 @  3  | | |5 
 2 @  1  |2 
 1 @  1  |1 
 8 @  5  | | | | |8 


In [47]:
#Usando bisect de outra maneira

def grade(score, breakpoints=(60,70,80,90), grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33,99,77,89,90,100]]

['F', 'A', 'C', 'B', 'A', 'A']

In [48]:
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE * 2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [49]:
#Array
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5963321947530882

In [50]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.5963321947530882

In [51]:
floats2 == floats

True

In [52]:
"""Arrays possuem quase todos os métodos e operações 
de uma list convencional, vá à página 78 de Fluent 
Python para vê-las ou busque na internet."""

'Arrays possuem quase todos os métodos e operações \nde uma list convencional, vá à página 78 de Fluent \nPython para vê-las ou busque na internet.'

In [1]:
#Numpy e Scipy
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
type(a)

numpy.ndarray

In [4]:
a.shape

(12,)

In [6]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a[2]

array([ 8,  9, 10, 11])

In [8]:
a[2, 1]

9

In [9]:
a[:, 1]

array([1, 5, 9])

In [10]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
floats = np.loadtxt('files/floats-10M-lines.txt')
floats[-3:]

array([97581.398591, 57586.213547, 79467.745898])

In [59]:
floats *= .5
floats[-3:]

array([48790.6992955, 28793.1067735, 39733.872949 ])

In [60]:
from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0

0.0004258879998815246

In [62]:
np.save('floats-10M', floats)
floats2 = np.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([97581.398591, 57586.213547, 79467.745898])

In [75]:
#Deques
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [77]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [78]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [80]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

In [81]:
"""Para saber mais sobre deque acesse a web ou página 85 de Fluente Python
Outras classes para se ver: 
Queue: Queue, LifoQueue, PriorityQueue
Multiprocessing
Asyncio
Heapq"""

'Para saber mais sobre deque acesse a web ou página 85 de Fluente Python'