In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index # como range(4)

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], 
                 index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
sdata = {'Ohio': 35000, 'Texas': 71000, 
         'Oregon': 16000, 'Utah': 5000}

In [18]:
obj3 = pd.Series(sdata)

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [21]:
obj4 = pd.Series(sdata, index=states)

In [22]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name = 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [34]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [35]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [36]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [39]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [40]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [41]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [42]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [43]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [44]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [45]:
frame2['debt'] = 16.5

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [47]:
frame2['debt'] = np.arange(6.)

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [49]:
val = pd.Series([-1.2, -1.5, -1.7], 
                index=['two', 'four', 'five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'

In [53]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [54]:
del(frame2['eastern'])

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2002: 3.6}}

In [57]:
frame3 = pd.DataFrame(pop)

In [58]:
frame3

Nevada  Ohio
2001     2.4   NaN
2002     2.9   3.6
2000     NaN   1.5

In [59]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     NaN   3.6   1.5

In [60]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   NaN
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [62]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   NaN     2.4
2002   3.6     2.9

In [63]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [64]:
frame3

state  Nevada  Ohio
year               
2001      2.4   NaN
2002      2.9   3.6
2000      NaN   1.5

In [65]:
# Possíveis entradas de dados para o construtor de DataFrame: pág 257

In [66]:
frame3.values

array([[2.4, nan],
       [2.9, 3.6],
       [nan, 1.5]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [68]:
# Objetos Index

In [69]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [70]:
index = obj.index

In [71]:
index

Index(['a', 'b', 'c'], dtype='object')

In [72]:
index[1:]

Index(['b', 'c'], dtype='object')

In [73]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [74]:
labels = pd.Index(np.arange(3))

In [75]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [76]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [77]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [78]:
frame3

state  Nevada  Ohio
year               
2001      2.4   NaN
2002      2.9   3.6
2000      NaN   1.5

In [79]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [80]:
'Ohio' in frame3.columns

True

In [81]:
2003 in frame3.index

False

In [82]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [83]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [84]:
# Alguns métodos e propriedades de Index: pág 261

In [85]:
# Funcionalidades Essenciais

In [86]:
# Reindexação

In [87]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], 
                index=['d', 'b', 'a', 'c'])

In [88]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [89]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [90]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [91]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], 
                 index=[0, 2, 4])

In [92]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [93]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [94]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [95]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [96]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [97]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [98]:
states = ['Texas', 'Utah', 'California']

In [99]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [100]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

In [ ]:
# Argumentos da função reindex: pág 266

In [101]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [102]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [103]:
new_obj = obj.drop('c')

In [104]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [105]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [106]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [107]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [108]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [109]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [110]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [111]:
obj.drop('c', inplace=True)

In [112]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [113]:
# Indexação, seleção e filtragem

In [114]:
obj = pd.Series(np.arange(4.), 
                index=['a', 'b', 'c', 'd'])

In [115]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [116]:
obj['d']

3.0

In [117]:
obj[1]

1.0

In [118]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [119]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [120]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [121]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [122]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [123]:
obj['b':'c'] = 5

In [124]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [125]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [126]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [128]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [129]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [130]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [131]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [132]:
data[data < 5] = 0

In [133]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
# Seleção loc e iloc

In [135]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [136]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [137]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [138]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [139]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [140]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [141]:
# Opções de indexação com DataFrame: pág 277

In [142]:
# Índices inteiros

In [143]:
ser = pd.Series(np.arange(3.))

In [144]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [145]:
ser[-1] # não funciona

KeyError: -1

In [146]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [147]:
ser2 = pd.Series(np.arange(3.), 
                 index=['a', 'b', 'c'])

In [148]:
ser2[-1]

2.0

In [149]:
ser[:1]

0    0.0
dtype: float64

In [150]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [151]:
ser.iloc[:1]

0    0.0
dtype: float64

In [152]:
# Aritmética e alinhamento de dados

In [153]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5],
              index=['a', 'c', 'd', 'e'])

In [154]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a', 'c', 'e', 'f', 'g'])

In [155]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [156]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [157]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [158]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                  columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])

In [159]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                  columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [160]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [161]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [162]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [163]:
df1 = pd.DataFrame({'A': [1, 2]})

In [164]:
df2 = pd.DataFrame({'B': [3, 4]})

In [165]:
df1

A
0  1
1  2

In [166]:
df2

B
0  3
1  4

In [167]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [168]:
# Métodos Aritméticos com valores para preenchimento

In [169]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [170]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [171]:
df2.loc[1, 'b'] = np.nan

In [172]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [173]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [174]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [175]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [176]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [177]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [178]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [179]:
# Métodos aritméticos flexíveis: pág 286

### Operações entre DataFrames e Series

In [180]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [181]:
arr[0]

array([0., 1., 2., 3.])

In [182]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [183]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [184]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [185]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [186]:
series2 = pd.Series(range(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int64

In [187]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [188]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [189]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [190]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Aplicação de funções e mapeamento

In [191]:
frame = pd.DataFrame(np.random.randn(4, 3),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah   -0.223823  0.343157 -0.221791
Ohio    0.310767 -1.279578  0.206387
Texas  -0.391439  1.116276 -0.365559
Oregon  1.045999  0.918333 -0.228418

In [192]:
np.abs(frame)

b         d         e
Utah    0.223823  0.343157  0.221791
Ohio    0.310767  1.279578  0.206387
Texas   0.391439  1.116276  0.365559
Oregon  1.045999  0.918333  0.228418

In [193]:
f = lambda x: x.max() - x.min()

In [194]:
frame.apply(f)

b    1.437439
d    2.395854
e    0.571946
dtype: float64

In [195]:
frame.apply(f, axis='columns')

Utah      0.566981
Ohio      1.590344
Texas     1.507716
Oregon    1.274417
dtype: float64

In [196]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [197]:
frame.apply(f)

b         d         e
min -0.391439 -1.279578 -0.365559
max  1.045999  1.116276  0.206387

In [198]:
format = lambda x: "%.2f" % x

In [199]:
frame.applymap(format)

b      d      e
Utah    -0.22   0.34  -0.22
Ohio     0.31  -1.28   0.21
Texas   -0.39   1.12  -0.37
Oregon   1.05   0.92  -0.23

In [200]:
frame['e'].map(format)

Utah      -0.22
Ohio       0.21
Texas     -0.37
Oregon    -0.23
Name: e, dtype: object

### Ordenação e classificação

In [201]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [202]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [203]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                      columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [204]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [205]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [206]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [207]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [208]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [209]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [210]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [211]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [212]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [213]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [214]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [215]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [216]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [217]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [218]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4.3  0
1  7.0  1
2 -3.0  0
3  2.0  1

In [219]:
frame.rank(axis='columns')

b    a
0  2.0  1.0
1  2.0  1.0
2  1.0  2.0
3  2.0  1.0

🗒️ Métodos de desempate com rank - pág 298

### Índices de eixos com rótulos duplicados

In [220]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [221]:
obj.index.is_unique

False

In [222]:
obj['a']

a    0
a    1
dtype: int64

In [223]:
obj['c']

4

In [224]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'd'])
df

0         1         2
a -0.030591  0.126503  0.790369
a  1.352974  0.227289 -0.493968
b  2.106824 -0.236242  0.118143
d -0.796048 -0.201526 -0.467417

In [225]:
df.loc['b']

0    2.106824
1   -0.236242
2    0.118143
Name: b, dtype: float64

## 5.3 Resumindo e calculando estatísticas descritivas

In [226]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [227]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [228]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [229]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

🗒️ Opções para os métodos de redução - pág 302

In [230]:
df.idxmax()

one    b
two    d
dtype: object

In [231]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [232]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [233]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [234]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

🗒️ Estatísticas descritivas e de resumo - pág 304

### Correlação e covariância

In [235]:
import pandas_datareader.data as web

In [236]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [237]:
price = pd.DataFrame({ticker: data['Adj Close']
                    for ticker, data in all_data.items()})

In [238]:
volume = pd.DataFrame({ticker: data['Volume']
                for ticker, data in all_data.items()})

In [239]:
returns = price.pct_change()
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2017-08-09       NaN       NaN       NaN       NaN
2017-08-10 -0.031852  0.000493 -0.014627 -0.016968
2017-08-11  0.013907  0.000000  0.015264  0.007881
2017-08-14  0.015050  0.003384  0.015034  0.009055
2017-08-15  0.010948 -0.001757  0.000273 -0.000488
...              ...       ...       ...       ...
2022-08-02 -0.009287 -0.001742 -0.011474  0.003637
2022-08-03  0.038248  0.004021  0.027836  0.024849
2022-08-04 -0.001926 -0.005289  0.004177  0.000758
2022-08-05 -0.001389  0.006381 -0.002609 -0.005468
2022-08-08 -0.003719  0.001283 -0.010382  0.000254

[1258 rows x 4 columns]

In [240]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-08-02 -0.009287 -0.001742 -0.011474  0.003637
2022-08-03  0.038248  0.004021  0.027836  0.024849
2022-08-04 -0.001926 -0.005289  0.004177  0.000758
2022-08-05 -0.001389  0.006381 -0.002609 -0.005468
2022-08-08 -0.003719  0.001283 -0.010382  0.000254

In [241]:
returns['MSFT'].corr(returns['IBM'])

0.47568539284112404

In [242]:
returns['MSFT'].cov(returns['IBM'])

0.00015259426265062934

In [243]:
returns.MSFT.corr(returns.IBM)

0.47568539284112404

In [244]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.434778  0.759612  0.685022
IBM   0.434778  1.000000  0.475685  0.443274
MSFT  0.759612  0.475685  1.000000  0.787014
GOOG  0.685022  0.443274  0.787014  1.000000

In [245]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000411  0.000151  0.000288  0.000260
IBM   0.000151  0.000294  0.000153  0.000142
MSFT  0.000288  0.000153  0.000350  0.000275
GOOG  0.000260  0.000142  0.000275  0.000350

In [246]:
returns.corrwith(returns.IBM)

AAPL    0.434778
IBM     1.000000
MSFT    0.475685
GOOG    0.443274
dtype: float64

In [247]:
returns.corrwith(volume)

AAPL   -0.081937
IBM    -0.114224
MSFT   -0.068702
GOOG   -0.081530
dtype: float64

### Valores únicos, contadores de valores e pertinência

In [249]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [250]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [251]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [252]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [253]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [255]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [256]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [257]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [258]:
unique_vals = pd.Series(['c', 'b', 'a'])
unique_vals

0    c
1    b
2    a
dtype: object

In [259]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

🗒️ Métodos para unicidade, contadores de valores e pertiência a conjuntos - pág 311

In [260]:
data = pd.DataFrame({
    'Qu1': [1, 3, 4, 3, 4],
    'Qu2': [2, 3, 1, 2, 3],
    'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [261]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

# Capítulo 6 
#### Carga de dados, armazenagem e formatos de arquivo