In [60]:
import pandas as pd
import numpy as np

In [61]:
obj = pd.Series([4, 7, -5, 3])

In [62]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [63]:
obj.values

array([ 4,  7, -5,  3])

In [64]:
obj.index # como range(4)

RangeIndex(start=0, stop=4, step=1)

In [65]:
obj2 = pd.Series([4, 7, -5, 3], 
                 index=['d', 'b', 'a', 'c'])

In [66]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [67]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [68]:
obj2['a']

-5

In [69]:
obj2['d'] = 6

In [70]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [71]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [72]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [73]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [74]:
'b' in obj2

True

In [75]:
'e' in obj2

False

In [76]:
sdata = {'Ohio': 35000, 'Texas': 71000, 
         'Oregon': 16000, 'Utah': 5000}

In [77]:
obj3 = pd.Series(sdata)

In [78]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [79]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [80]:
obj4 = pd.Series(sdata, index=states)

In [81]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [82]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [83]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [84]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [85]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [86]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [87]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [88]:
obj4.name = 'population'

In [89]:
obj4.index.name = 'state'

In [90]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [91]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [92]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [93]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [94]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [95]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [96]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [97]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [98]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [99]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [100]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [101]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [102]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [103]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [104]:
frame2['debt'] = 16.5

In [105]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [106]:
frame2['debt'] = np.arange(6.)

In [107]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [108]:
val = pd.Series([-1.2, -1.5, -1.7], 
                index=['two', 'four', 'five'])

In [109]:
frame2['debt'] = val

In [110]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [111]:
frame2['eastern'] = frame2.state == 'Ohio'

In [112]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [113]:
del(frame2['eastern'])

In [114]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [115]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2002: 3.6}}

In [116]:
frame3 = pd.DataFrame(pop)

In [117]:
frame3

Nevada  Ohio
2001     2.4   NaN
2002     2.9   3.6
2000     NaN   1.5

In [118]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     NaN   3.6   1.5

In [119]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   NaN
2002     2.9   3.6
2003     NaN   NaN

In [120]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [121]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   NaN     2.4
2002   3.6     2.9

In [122]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [123]:
frame3

state  Nevada  Ohio
year               
2001      2.4   NaN
2002      2.9   3.6
2000      NaN   1.5

In [124]:
# Possíveis entradas de dados para o construtor de DataFrame: pág 257

In [125]:
frame3.values

array([[2.4, nan],
       [2.9, 3.6],
       [nan, 1.5]])

In [126]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [127]:
# Objetos Index

In [128]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [129]:
index = obj.index

In [130]:
index

Index(['a', 'b', 'c'], dtype='object')

In [131]:
index[1:]

Index(['b', 'c'], dtype='object')

In [132]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [ ]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   NaN
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3.index

False

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [ ]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
# Alguns métodos e propriedades de Index: pág 261

In [ ]:
# Funcionalidades Essenciais

In [ ]:
# Reindexação

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], 
                index=['d', 'b', 'a', 'c'])

In [ ]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [ ]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], 
                 index=[0, 2, 4])

In [ ]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [ ]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [ ]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
states = ['Texas', 'Utah', 'California']

In [ ]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
frame.loc[['a', 'b', 'c', 'd'], states]

<class 'KeyError'>: "['b'] not in index"

In [ ]:
# Argumentos da função reindex: pág 266

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')

In [ ]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
obj.drop('c', inplace=True)

In [ ]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
# Indexação, seleção e filtragem

In [ ]:
obj = pd.Series(np.arange(4.), 
                index=['a', 'b', 'c', 'd'])

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['d']

3.0

In [ ]:
obj[1]

1.0

In [ ]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [ ]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [ ]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [ ]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [ ]:
obj['b':'c'] = 5

In [ ]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [ ]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [ ]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data < 5] = 0

In [ ]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# Seleção loc e iloc

In [ ]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [ ]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [ ]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [ ]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [ ]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
# Opções de indexação com DataFrame: pág 277

In [ ]:
# Índices inteiros

In [ ]:
ser = pd.Series(np.arange(3.))

In [ ]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [ ]:
ser[-1] # não funciona

<class 'KeyError'>: -1

In [ ]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [ ]:
ser2 = pd.Series(np.arange(3.), 
                 index=['a', 'b', 'c'])

In [ ]:
ser2[-1]

2.0

In [ ]:
ser[:1]

0    0.0
dtype: float64

In [ ]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [ ]:
ser.iloc[:1]

0    0.0
dtype: float64

In [ ]:
# Aritmética e alinhamento de dados

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5],
              index=['a', 'c', 'd', 'e'])

In [ ]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                  columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])

In [ ]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                  columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [ ]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:
df1 = pd.DataFrame({'A': [1, 2]})

In [ ]:
df2 = pd.DataFrame({'B': [3, 4]})

In [ ]:
df1

A
0  1
1  2

In [ ]:
df2

B
0  3
1  4

In [ ]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [ ]:
# Métodos Aritméticos com valores para preenchimento

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [ ]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [ ]:
df2.loc[1, 'b'] = np.nan

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [ ]:
# Métodos aritméticos flexíveis: pág 286

### Operações entre DataFrames e Series

In [133]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [134]:
arr[0]

array([0., 1., 2., 3.])

In [135]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [137]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [138]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [139]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [140]:
series2 = pd.Series(range(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int64

In [141]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [143]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [144]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [145]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Aplicação de funções e mapeamento

In [146]:
frame = pd.DataFrame(np.random.randn(4, 3),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah   -1.172244 -0.403218 -1.206705
Ohio    0.753016  1.009784  0.897797
Texas   0.379625  2.354079  0.835799
Oregon -0.804938  0.128281  0.249487

In [147]:
np.abs(frame)

b         d         e
Utah    1.172244  0.403218  1.206705
Ohio    0.753016  1.009784  0.897797
Texas   0.379625  2.354079  0.835799
Oregon  0.804938  0.128281  0.249487

In [148]:
f = lambda x: x.max() - x.min()

In [151]:
frame.apply(f)

b    1.925260
d    2.757297
e    2.104503
dtype: float64

In [153]:
frame.apply(f, axis='columns')

Utah      0.803487
Ohio      0.256768
Texas     1.974454
Oregon    1.054424
dtype: float64

In [154]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [155]:
frame.apply(f)

b         d         e
min -1.172244 -0.403218 -1.206705
max  0.753016  2.354079  0.897797

In [156]:
format = lambda x: "%.2f" % x

In [157]:
frame.applymap(format)

b      d      e
Utah    -1.17  -0.40  -1.21
Ohio     0.75   1.01   0.90
Texas    0.38   2.35   0.84
Oregon  -0.80   0.13   0.25

In [158]:
frame['e'].map(format)

Utah      -1.21
Ohio       0.90
Texas      0.84
Oregon     0.25
Name: e, dtype: object

### Ordenação e classificação

In [160]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [161]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [163]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                      columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [164]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [165]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [166]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [167]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [168]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [169]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [170]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [171]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [172]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [173]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [174]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [175]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [176]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [177]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [178]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4.3  0
1  7.0  1
2 -3.0  0
3  2.0  1

In [179]:
frame.rank(axis='columns')

b    a
0  2.0  1.0
1  2.0  1.0
2  1.0  2.0
3  2.0  1.0

🗒️ Métodos de desempate com rank - pág 298

### Índices de eixos com rótulos duplicados

In [180]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [181]:
obj.index.is_unique

False

In [182]:
obj['a']

a    0
a    1
dtype: int64

In [183]:
obj['c']

4

In [185]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'd'])
df

0         1         2
a  0.265080 -0.507073  1.637765
a  0.928291 -0.066204  0.200093
b  0.045527  0.980030 -0.387401
d  0.869843 -1.225831  0.857872

In [186]:
df.loc['b']

0    0.045527
1    0.980030
2   -0.387401
Name: b, dtype: float64

## Resumindo e calculando estatísticas descritivas