In [1]:
import pandas as pd
import numpy as np

# Capítulo 7 - Limpeza e preparação dos dados

## 7.1 - Tratando dados ausentes

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None

In [5]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

🗒️ Métodos para tratamento de NA - pág 361

### Filtrando dados ausentes

In [6]:
from numpy import nan as NA

In [7]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [8]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1., 6.5, 3.], 
                     [1., NA, NA],
                     [NA, NA, NA],
                     [NA, 6.5, 3.]])

In [11]:
cleaned = data.dropna()

In [12]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4] = NA

In [15]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.randn(7, 3))

In [18]:
df.iloc[:4, 1] = NA

In [19]:
df.iloc[:2, 2] = NA

In [20]:
df

0         1         2
0 -1.750159       NaN       NaN
1  0.271752       NaN       NaN
2 -0.060177       NaN  0.530584
3  0.848269       NaN  0.273571
4  0.526709  0.464835  1.182756
5 -0.556800  0.982233 -0.264120
6 -1.882997  0.753536  2.033396

In [21]:
df.dropna()

0         1         2
4  0.526709  0.464835  1.182756
5 -0.556800  0.982233 -0.264120
6 -1.882997  0.753536  2.033396

In [22]:
df.dropna(thresh=2)

0         1         2
2 -0.060177       NaN  0.530584
3  0.848269       NaN  0.273571
4  0.526709  0.464835  1.182756
5 -0.556800  0.982233 -0.264120
6 -1.882997  0.753536  2.033396

### Preenchendo dados ausentes

In [23]:
df.fillna(0)

0         1         2
0 -1.750159  0.000000  0.000000
1  0.271752  0.000000  0.000000
2 -0.060177  0.000000  0.530584
3  0.848269  0.000000  0.273571
4  0.526709  0.464835  1.182756
5 -0.556800  0.982233 -0.264120
6 -1.882997  0.753536  2.033396

In [24]:
df.fillna({1: 0.5, 2:0})

0         1         2
0 -1.750159  0.500000  0.000000
1  0.271752  0.500000  0.000000
2 -0.060177  0.500000  0.530584
3  0.848269  0.500000  0.273571
4  0.526709  0.464835  1.182756
5 -0.556800  0.982233 -0.264120
6 -1.882997  0.753536  2.033396

In [25]:
_ = df.fillna(0, inplace=True)

In [26]:
df

0         1         2
0 -1.750159  0.000000  0.000000
1  0.271752  0.000000  0.000000
2 -0.060177  0.000000  0.530584
3  0.848269  0.000000  0.273571
4  0.526709  0.464835  1.182756
5 -0.556800  0.982233 -0.264120
6 -1.882997  0.753536  2.033396

In [27]:
df = pd.DataFrame(np.random.randn(6, 3))

In [28]:
df.iloc[2:, 1] = NA

In [29]:
df.iloc[:4, 2] = NA

In [30]:
df

0         1         2
0 -0.886377  1.607580       NaN
1  0.379029  0.688096       NaN
2  0.666640       NaN       NaN
3  0.602654       NaN       NaN
4  2.576167       NaN -1.018654
5 -0.184883       NaN  0.394468

In [31]:
df.fillna(method='ffill')

0         1         2
0 -0.886377  1.607580       NaN
1  0.379029  0.688096       NaN
2  0.666640  0.688096       NaN
3  0.602654  0.688096       NaN
4  2.576167  0.688096 -1.018654
5 -0.184883  0.688096  0.394468

In [32]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [33]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

🗒️ Argumentos da função fillna - pág 368

## 7.2 - Transformação de dados

### Removendo duplicatas

In [34]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [35]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [36]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [37]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [38]:
data['v1'] = range(7)

In [39]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [40]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [41]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transformando dados usando uma função ou um mapeamento

In [42]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],
                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [43]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [44]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [45]:
lowercased = data['food'].str.lower()

In [46]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [47]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Substituindo valores

In [48]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [49]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [50]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [51]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [52]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [53]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renomeando os índices dos eixos

In [54]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [55]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [56]:
transform = lambda x: x[:4].upper()

In [57]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [58]:
data.index = data.index.map(transform)

In [59]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [60]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [61]:
data.rename(index={'OHIO': 'INDIANA'}, 
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [62]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [63]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### Discretização e compartimentalização (binning)

In [64]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [65]:
bins = [18, 25, 35, 60, 100]

In [66]:
cats = pd.cut(ages, bins)

In [67]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [68]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [69]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [70]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [71]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [72]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [73]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [74]:
data = np.random.rand(20)

In [75]:
data

array([0.73233557, 0.86815706, 0.85827082, 0.90024215, 0.72649692,
       0.07953936, 0.36708225, 0.25766512, 0.5410671 , 0.64264022,
       0.76506188, 0.9060496 , 0.46629219, 0.68896648, 0.53699939,
       0.44831206, 0.71078839, 0.96281325, 0.33346396, 0.78068749])

In [76]:
pd.cut(data, 4, precision=2)

[(0.52, 0.74], (0.74, 0.96], (0.74, 0.96], (0.74, 0.96], (0.52, 0.74], ..., (0.3, 0.52], (0.52, 0.74], (0.74, 0.96], (0.3, 0.52], (0.74, 0.96]]
Length: 20
Categories (4, interval[float64, right]): [(0.079, 0.3] < (0.3, 0.52] < (0.52, 0.74] < (0.74, 0.96]]

In [77]:
data = np.random.randn(1000)

In [78]:
cats = pd.qcut(data, 4)

In [79]:
cats

[(-3.803, -0.711], (0.61, 3.341], (0.61, 3.341], (-0.0492, 0.61], (-3.803, -0.711], ..., (0.61, 3.341], (-3.803, -0.711], (-0.0492, 0.61], (-3.803, -0.711], (-0.711, -0.0492]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.803, -0.711] < (-0.711, -0.0492] < (-0.0492, 0.61] < (0.61, 3.341]]

In [80]:
pd.value_counts(cats)

(-3.803, -0.711]     250
(-0.711, -0.0492]    250
(-0.0492, 0.61]      250
(0.61, 3.341]        250
dtype: int64

In [81]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.371, -0.0492], (1.249, 3.341], (1.249, 3.341], (-0.0492, 1.249], (-3.803, -1.371], ..., (-0.0492, 1.249], (-1.371, -0.0492], (-0.0492, 1.249], (-3.803, -1.371], (-1.371, -0.0492]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.803, -1.371] < (-1.371, -0.0492] < (-0.0492, 1.249] < (1.249, 3.341]]

### Detectando e filtrando valores discrepantes

In [82]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [83]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.029537     0.031291    -0.026828     0.005331
std       0.952172     0.969562     0.998474     1.018011
min      -3.310356    -3.598833    -3.466090    -3.113414
25%      -0.693451    -0.624190    -0.672570    -0.627257
50%      -0.043127     0.034049    -0.011799     0.003416
75%       0.600228     0.703748     0.617650     0.693752
max       3.196417     3.195955     3.117929     3.343195

In [84]:
col = data[2]

In [85]:
col[np.abs(col) > 3]

416   -3.466090
518    3.117929
Name: 2, dtype: float64

In [86]:
data[(np.abs(data > 3).any(1))]

0         1         2         3
144 -0.666265  3.170309 -0.503194 -1.632821
386  0.201631  3.195955  0.536789  0.262773
479  3.196417  0.982693 -0.327091 -0.368165
518 -0.741622 -0.060684  3.117929 -0.900801
709  0.296610  1.349136 -0.798550  3.343195

In [87]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [88]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.029423     0.031524    -0.026480     0.005101
std       0.950505     0.966340     0.996609     1.016600
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.693451    -0.624190    -0.672570    -0.627257
50%      -0.043127     0.034049    -0.011799     0.003416
75%       0.600228     0.703748     0.617650     0.693752
max       3.000000     3.000000     3.000000     3.000000

In [89]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0  1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0 -1.0  1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4  1.0  1.0 -1.0 -1.0

### Permutação e amostragem aleatória

In [90]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [91]:
sampler = np.random.permutation(5)

In [92]:
sampler

array([3, 2, 4, 1, 0])

In [93]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [94]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3

In [95]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [96]:
choices = pd.Series([5, 7, -1, 6, 4])

In [97]:
draws = choices.sample(n=10, replace=True)

In [98]:
draws

3    6
0    5
3    6
0    5
3    6
1    7
2   -1
3    6
3    6
0    5
dtype: int64

### Calculando variáveis indicadoras/dummy

In [99]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [100]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [101]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [102]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [103]:
df_with_dummy = df[['data1']].join(dummies)

In [104]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [105]:
mnames = ['movie_id', 'title', 'genres']

In [106]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)

/tmp/ipykernel_35168/4223470057.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('datasets/movielens/movies.dat', sep='::',


In [107]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [108]:
all_genres = []

In [109]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [110]:
genres = pd.unique(all_genres)

In [111]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [112]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [113]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [114]:
gen = movies.genres[0]

In [115]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [116]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [117]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [118]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [119]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                              1.0
Genre_Children's                             1.0
Genre_Comedy                                 1.0
Genre_Adventure                              0.0
Genre_Fantasy                                0.0
Genre_Romance                                0.0
Genre_Drama                                  0.0
Genre_Action                                 0.0
Genre_Crime                                  0.0
Genre_Thriller                               0.0
Genre_Horror                                 0.0
Genre_Sci-Fi                                 0.0
Genre_Documentary                            0.0
Genre_War                                    0.0
Genre_Musical                                0.0
Genre_Mystery                                0.0
Genre_Film-Noir                              0.0
Genre_Western       

In [120]:
np.random.seed(12345)

In [121]:
values = np.random.rand(10)

In [122]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [123]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [124]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 - Manipulação de strings

### Métodos de objetos string

In [125]:
val = 'a,b, guido'
val.split()

['a,b,', 'guido']

In [126]:
pieces = [x.strip() for x in val.split(',')]

In [127]:
pieces

['a', 'b', 'guido']

In [128]:
first, second, third = pieces

In [129]:
first + '::' + second + '::' + third

'a::b::guido'

In [130]:
'::'.join(pieces)

'a::b::guido'

In [131]:
'guido' in val

True

In [132]:
val.index(',')

1

In [133]:
val.find(':')

-1

In [135]:
# dá erro
# val.index(':')

In [136]:
val.count(',')

2

In [137]:
val.replace(',', '::')

'a::b:: guido'

In [138]:
val.replace(',', '')

'ab guido'

🗒️ Métodos embutidos de string em python - pág 396

### Expressões regulares

In [139]:
import re

In [140]:
text = "foo bar\t baz \tqux"

In [141]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [142]:
regex = re.compile('\s+')

In [143]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [145]:
regex.findall(text)

[' ', '\t ', ' \t']

In [183]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [184]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [185]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [186]:
m = regex.search(text)

In [187]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [188]:
text[m.start():m.end()]

'dave@google.com'

In [189]:
print(regex.match(text))

None


In [190]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [198]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [199]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [200]:
m = regex.match('wesm@bright.net')

In [201]:
m.groups()

('wesm', 'bright', 'net')

In [202]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [203]:
print(regex.sub(r'Username \1, Domain: \2, Sufix: \3', text))

Dave Username dave, Domain: google, Sufix: com
Steve Username steve, Domain: gmail, Sufix: com
Rob Username rob, Domain: gmail, Sufix: com
Ryan Username ryan, Domain: yahoo, Sufix: com


🗒️ Métodos de expressões regulares - pág 402

### Funções de string vetorizadas no pandas

In [224]:
data = {'Dave': 'dave@google.com',
        'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com',
        'Wes': np.nan}

In [225]:
data = pd.Series(data)

In [226]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [227]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [228]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [229]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [230]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [231]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [232]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [240]:
data.str.get(1)

Dave       a
Steve      t
Rob        o
Wes      NaN
dtype: object

In [244]:
data.str[0]

Dave       d
Steve      s
Rob        r
Wes      NaN
dtype: object

In [245]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

🗒️ Listagem parcial dos métodos de string vetorizados - pág 406