In [1]:
import pandas as pd
import numpy as np

# Capítulo 7 - Limpeza e preparação dos dados

## 7.1 - Tratando dados ausentes

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None

In [5]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

🗒️ Métodos para tratamento de NA - pág 361

### Filtrando dados ausentes

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data = pd.DataFrame([[1., 6.5, 3.], 
                     [1., NA, NA],
                     [NA, NA, NA],
                     [NA, 6.5, 3.]])

In [14]:
cleaned = data.dropna()

In [15]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [16]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data[4] = NA

In [18]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [19]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
df = pd.DataFrame(np.random.randn(7, 3))

In [21]:
df.iloc[:4, 1] = NA

In [22]:
df.iloc[:2, 2] = NA

In [23]:
df

0         1         2
0 -0.508976       NaN       NaN
1 -1.199330       NaN       NaN
2  0.652772       NaN -1.191531
3 -1.383967       NaN -0.749246
4  0.434794  1.660020  1.600449
5  0.178168 -0.674600  0.346298
6 -0.908420 -0.071832  0.500035

In [24]:
df.dropna()

0         1         2
4  0.434794  1.660020  1.600449
5  0.178168 -0.674600  0.346298
6 -0.908420 -0.071832  0.500035

In [25]:
df.dropna(thresh=2)

0         1         2
2  0.652772       NaN -1.191531
3 -1.383967       NaN -0.749246
4  0.434794  1.660020  1.600449
5  0.178168 -0.674600  0.346298
6 -0.908420 -0.071832  0.500035

### Preenchendo dados ausentes

In [26]:
df.fillna(0)

0         1         2
0 -0.508976  0.000000  0.000000
1 -1.199330  0.000000  0.000000
2  0.652772  0.000000 -1.191531
3 -1.383967  0.000000 -0.749246
4  0.434794  1.660020  1.600449
5  0.178168 -0.674600  0.346298
6 -0.908420 -0.071832  0.500035

In [27]:
df.fillna({1: 0.5, 2:0})

0         1         2
0 -0.508976  0.500000  0.000000
1 -1.199330  0.500000  0.000000
2  0.652772  0.500000 -1.191531
3 -1.383967  0.500000 -0.749246
4  0.434794  1.660020  1.600449
5  0.178168 -0.674600  0.346298
6 -0.908420 -0.071832  0.500035

In [28]:
_ = df.fillna(0, inplace=True)

In [29]:
df

0         1         2
0 -0.508976  0.000000  0.000000
1 -1.199330  0.000000  0.000000
2  0.652772  0.000000 -1.191531
3 -1.383967  0.000000 -0.749246
4  0.434794  1.660020  1.600449
5  0.178168 -0.674600  0.346298
6 -0.908420 -0.071832  0.500035

In [30]:
df = pd.DataFrame(np.random.randn(6, 3))

In [31]:
df.iloc[2:, 1] = NA

In [32]:
df.iloc[:4, 2] = NA

In [33]:
df

0         1         2
0 -0.001428  0.661729       NaN
1 -1.173773  0.016511       NaN
2 -1.757941       NaN       NaN
3 -0.079691       NaN       NaN
4  1.268791       NaN -0.809698
5 -0.233182       NaN  0.762000

In [34]:
df.fillna(method='ffill')

0         1         2
0 -0.001428  0.661729       NaN
1 -1.173773  0.016511       NaN
2 -1.757941  0.016511       NaN
3 -0.079691  0.016511       NaN
4  1.268791  0.016511 -0.809698
5 -0.233182  0.016511  0.762000

In [35]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [36]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

🗒️ Argumentos da função fillna - pág 368

## 7.2 - Transformação de dados

### Removendo duplicatas

In [37]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [38]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data['v1'] = range(7)

In [42]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [43]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transformando dados usando uma função ou um mapeamento

In [46]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],
                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [49]:
lowercased = data['food'].str.lower()

In [50]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [51]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Substituindo valores

In [52]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [53]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [54]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [56]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [57]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renomeando os índices dos eixos

In [58]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [59]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [60]:
transform = lambda x: x[:4].upper()

In [61]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [62]:
data.index = data.index.map(transform)

In [63]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [64]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [65]:
data.rename(index={'OHIO': 'INDIANA'}, 
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [66]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [67]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### Discretização e compartimentalização (binning)

In [68]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [69]:
bins = [18, 25, 35, 60, 100]

In [71]:
cats = pd.cut(ages, bins)

In [72]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [73]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [74]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [75]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [77]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [78]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [79]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [81]:
data = np.random.rand(20)

In [83]:
data

array([0.51357004, 0.7566508 , 0.98588457, 0.11244445, 0.06659152,
       0.69439996, 0.83108246, 0.53703621, 0.71701358, 0.82380138,
       0.70344748, 0.41774925, 0.66659764, 0.84279206, 0.48276771,
       0.85708418, 0.74133185, 0.38035769, 0.86374082, 0.6711393 ])

In [82]:
pd.cut(data, 4, precision=2)

[(0.3, 0.53], (0.76, 0.99], (0.76, 0.99], (0.066, 0.3], (0.066, 0.3], ..., (0.76, 0.99], (0.53, 0.76], (0.3, 0.53], (0.76, 0.99], (0.53, 0.76]]
Length: 20
Categories (4, interval[float64, right]): [(0.066, 0.3] < (0.3, 0.53] < (0.53, 0.76] < (0.76, 0.99]]

In [84]:
data = np.random.randn(1000)

In [85]:
cats = pd.qcut(data, 4)

In [86]:
cats

[(-0.716, -0.0481], (-3.198, -0.716], (-3.198, -0.716], (-0.716, -0.0481], (-3.198, -0.716], ..., (-0.716, -0.0481], (0.632, 3.337], (-0.716, -0.0481], (-3.198, -0.716], (0.632, 3.337]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.198, -0.716] < (-0.716, -0.0481] < (-0.0481, 0.632] < (0.632, 3.337]]

In [87]:
pd.value_counts(cats)

(-3.198, -0.716]     250
(-0.716, -0.0481]    250
(-0.0481, 0.632]     250
(0.632, 3.337]       250
dtype: int64

In [88]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.304, -0.0481], (-1.304, -0.0481], (-1.304, -0.0481], (-1.304, -0.0481], (-1.304, -0.0481], ..., (-1.304, -0.0481], (-0.0481, 1.32], (-1.304, -0.0481], (-1.304, -0.0481], (1.32, 3.337]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.198, -1.304] < (-1.304, -0.0481] < (-0.0481, 1.32] < (1.32, 3.337]]

### Detectando e filtrando valores discrepantes

In [90]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [91]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.001868     0.061424    -0.046667    -0.058114
std       1.028763     1.039179     1.001186     1.005753
min      -3.292250    -3.085762    -3.032545    -3.569426
25%      -0.721387    -0.673531    -0.713773    -0.733492
50%      -0.032082     0.031919    -0.051594    -0.073531
75%       0.735202     0.752539     0.619712     0.622524
max       2.922555     3.875910     3.424327     3.330626

In [92]:
col = data[2]

In [93]:
col[np.abs(col) > 3]

282    3.060187
326    3.424327
505   -3.032545
836    3.338663
961   -3.026138
Name: 2, dtype: float64

In [94]:
data[(np.abs(data > 3).any(1))]

0         1         2         3
176  0.168773  3.228915  0.460504 -0.817680
254  0.541206  0.308064 -0.441761  3.117418
282  1.716372 -0.889387  3.060187 -1.018676
326  0.324777  0.968200  3.424327 -0.146328
553  1.067373 -0.822428 -0.668039  3.327502
666  0.375500 -1.013051 -1.812710  3.021050
668 -1.917670  3.875910  0.174011  0.569641
836  1.132781 -0.309632  3.338663  1.284105
890  1.971482  0.940494  1.280038  3.330626
919 -0.897430  2.591310  0.416143  3.180390
963 -0.584489  3.820097 -1.273979  0.219462

In [95]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [96]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.001460     0.059667    -0.047431    -0.058251
std       1.027524     1.032484     0.998351     0.999974
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.721387    -0.673531    -0.713773    -0.733492
50%      -0.032082     0.031919    -0.051594    -0.073531
75%       0.735202     0.752539     0.619712     0.622524
max       2.922555     3.000000     3.000000     3.000000

In [97]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0 -1.0  1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4  1.0  1.0  1.0 -1.0

### Permutação e amostragem aleatória

In [98]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [99]:
sampler = np.random.permutation(5)

In [100]:
sampler

array([0, 3, 1, 2, 4])

In [101]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [102]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
4  16  17  18  19

In [103]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [104]:
choices = pd.Series([5, 7, -1, 6, 4])

In [105]:
draws = choices.sample(n=10, replace=True)

In [106]:
draws

2   -1
0    5
1    7
3    6
3    6
2   -1
4    4
2   -1
3    6
1    7
dtype: int64

### Calculando variáveis indicadoras/dummy

In [107]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [108]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [109]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [112]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [110]:
df_with_dummy = df[['data1']].join(dummies)

In [111]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [113]:
mnames = ['movie_id', 'title', 'genres']

In [115]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)

/tmp/ipykernel_11182/4223470057.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('datasets/movielens/movies.dat', sep='::',


In [116]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [117]:
all_genres = []

In [118]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [119]:
genres = pd.unique(all_genres)

In [120]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [121]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [123]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [124]:
gen = movies.genres[0]

In [125]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [126]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [127]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [128]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [129]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                              1.0
Genre_Children's                             1.0
Genre_Comedy                                 1.0
Genre_Adventure                              0.0
Genre_Fantasy                                0.0
Genre_Romance                                0.0
Genre_Drama                                  0.0
Genre_Action                                 0.0
Genre_Crime                                  0.0
Genre_Thriller                               0.0
Genre_Horror                                 0.0
Genre_Sci-Fi                                 0.0
Genre_Documentary                            0.0
Genre_War                                    0.0
Genre_Musical                                0.0
Genre_Mystery                                0.0
Genre_Film-Noir                              0.0
Genre_Western       

In [130]:
np.random.seed(12345)

In [133]:
values = np.random.rand(10)

In [136]:
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

In [137]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [138]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           1           0           0           0           0
3           1           0           0           0           0
4           0           1           0           0           0
5           0           0           0           1           0
6           0           0           0           0           1
7           0           0           0           0           1
8           0           0           0           0           1
9           0           0           0           1           0

## 7.3 - Manipulação de strings