In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1_000_000)

In [4]:
my_list = list(range(1_000_000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 21.1 ms, sys: 16.2 ms, total: 37.3 ms
Wall time: 36.3 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 868 ms, sys: 159 ms, total: 1.03 s
Wall time: 1.02 s


In [8]:
data = np.random.randn(2, 3)
data

array([[-0.03825732,  1.47686249,  0.64799498],
       [ 1.01983325, -1.92985954, -0.86291651]])

In [9]:
data * 10

array([[ -0.38257323,  14.76862486,   6.47994979],
       [ 10.19833251, -19.29859536,  -8.62916509]])

In [10]:
data + data

array([[-0.07651465,  2.95372497,  1.29598996],
       [ 2.0396665 , -3.85971907, -1.72583302]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [16]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.empty((2, 3, 2))

array([[[6.94659303e-310, 6.94659303e-310],
        [1.29441743e-312, 2.33419537e-312],
        [9.76118064e-313, 2.41907520e-312]],

       [[2.05833592e-312, 8.48798317e-313],
        [2.05833592e-312, 2.05833592e-312],
        [8.70018275e-313, 2.05833592e-312]]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [37]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [42]:
arr = np.array([1, 2, 3, 4, 5])

In [43]:
arr.dtype

dtype('int64')

In [44]:
float_arr = arr.astype(np.float64)

In [45]:
float_arr.dtype

dtype('float64')

In [46]:
arr = np.array([3.7, -1.2, 0.5, 12.9, 10.1])

In [47]:
arr

array([ 3.7, -1.2,  0.5, 12.9, 10.1])

In [48]:
arr.astype(np.int32)

array([ 3, -1,  0, 12, 10], dtype=int32)

In [51]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [57]:
numeric_strings.astype(float) #poderia usar também np.float64

array([ 1.25, -9.6 , 42.  ])

In [58]:
int_array = np.arange(10)

In [60]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [61]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
empty_uint32 = np.empty(8, dtype='u4')

In [63]:
empty_uint32

array([3784781520,      32735,  550886736,      32736,  551075920,
            32736,  551076240,      32736], dtype=uint32)

In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [66]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [71]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [73]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [74]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[5]

5

In [76]:
arr[5:8]

array([5, 6, 7])

In [79]:
arr[5:8] = 12

In [80]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [81]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [82]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [83]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [84]:
#Caso queira realmente fazer uma cópia
arr_copy = arr[5:8]
arr_copy

array([64, 64, 64])

In [85]:
arr_copy = 32
arr_copy

32

In [86]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [87]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [88]:
arr2d[0][2]

3

In [89]:
arr2d[0, 2]

3

In [95]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
old_values = arr3d[0].copy()

In [98]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
arr3d[1, 0]

array([7, 8, 9])

In [101]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [102]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [103]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [106]:
arr2d[1, :2]

array([4, 5])

In [107]:
arr2d[:2, 2]

array([3, 6])

In [108]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [109]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [112]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [113]:
data

array([[ 0.44501083,  0.22528418,  2.01652249, -1.74575414],
       [ 0.84188945, -0.95380029,  1.9672082 , -0.07743487],
       [ 0.83877734, -0.31850808, -0.85743202,  1.36672628],
       [ 0.59634104,  0.2132892 , -0.01646267, -0.05514709],
       [ 1.64895358, -0.79380735, -0.94571574,  1.60999928],
       [-1.29723385,  2.2071412 , -0.4609814 , -0.28853794],
       [-0.13893019,  0.86676056,  1.52707596,  1.44232334]])

In [114]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [115]:
data[names == 'Bob']

array([[ 0.44501083,  0.22528418,  2.01652249, -1.74575414],
       [ 0.59634104,  0.2132892 , -0.01646267, -0.05514709]])

In [116]:
data[names == 'Bob', 2:]

array([[ 2.01652249, -1.74575414],
       [-0.01646267, -0.05514709]])

In [117]:
data[names == 'Bob', 3]

array([-1.74575414, -0.05514709])

In [118]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [119]:
data[~(names == 'Bob')]

array([[ 0.84188945, -0.95380029,  1.9672082 , -0.07743487],
       [ 0.83877734, -0.31850808, -0.85743202,  1.36672628],
       [ 1.64895358, -0.79380735, -0.94571574,  1.60999928],
       [-1.29723385,  2.2071412 , -0.4609814 , -0.28853794],
       [-0.13893019,  0.86676056,  1.52707596,  1.44232334]])

In [120]:
cond = names == 'Bob'
data[~cond]

array([[ 0.84188945, -0.95380029,  1.9672082 , -0.07743487],
       [ 0.83877734, -0.31850808, -0.85743202,  1.36672628],
       [ 1.64895358, -0.79380735, -0.94571574,  1.60999928],
       [-1.29723385,  2.2071412 , -0.4609814 , -0.28853794],
       [-0.13893019,  0.86676056,  1.52707596,  1.44232334]])

In [121]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [123]:
data[mask]

array([[ 0.44501083,  0.22528418,  2.01652249, -1.74575414],
       [ 0.83877734, -0.31850808, -0.85743202,  1.36672628],
       [ 0.59634104,  0.2132892 , -0.01646267, -0.05514709],
       [ 1.64895358, -0.79380735, -0.94571574,  1.60999928]])

In [ ]:
"""Selecionar dados de um array com indexação 
booleana sempre criará uma cópia dos dados"""

In [125]:
data[data < 0] = 0
data

array([[0.44501083, 0.22528418, 2.01652249, 0.        ],
       [0.84188945, 0.        , 1.9672082 , 0.        ],
       [0.83877734, 0.        , 0.        , 1.36672628],
       [0.59634104, 0.2132892 , 0.        , 0.        ],
       [1.64895358, 0.        , 0.        , 1.60999928],
       [0.        , 2.2071412 , 0.        , 0.        ],
       [0.        , 0.86676056, 1.52707596, 1.44232334]])

In [126]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.84188945, 0.        , 1.9672082 , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 2.2071412 , 0.        , 0.        ],
       [0.        , 0.86676056, 1.52707596, 1.44232334]])

In [ ]:
# Indexação sofisticada

In [127]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [128]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [129]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [130]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [131]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [132]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [133]:
#indexação sofisticada sempre copia os dados

In [ ]:
#Transposição de arrays e troca de eixos
#transposição é uma forma especial de reformatação que, 
#de modo semelhante, devolve uma vizualização dos dados 
#subjacentes, sem copiar nada.

In [134]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [135]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [136]:
arr = np.random.randn(6, 3)
arr

array([[ 0.34953415, -0.29610039,  0.57821971],
       [ 1.68967834,  2.15210036,  1.62227501],
       [ 0.79666242, -1.61757059, -0.07175157],
       [-0.6107792 , -2.46981634, -0.41546455],
       [ 0.51409095, -0.0670492 ,  0.75819086],
       [ 0.18167155,  1.18708497, -2.18551441]])

In [137]:
np.dot(arr.T, arr)

array([[ 4.28220332,  3.9339051 ,  3.13255906],
       [ 3.9339051 , 14.84940511,  1.81704451],
       [ 3.13255906,  1.81704451,  8.49519994]])

In [139]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [140]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [141]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [142]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])