In [16]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index # como range(4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], 
                 index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 
         'Oregon': 16000, 'Utah': 5000}

In [23]:
obj3 = pd.Series(sdata)

In [24]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [26]:
obj4 = pd.Series(sdata, index=states)

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
obj4.name = 'population'

In [35]:
obj4.index.name = 'state'

In [36]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [39]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [40]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [41]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [45]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [46]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [47]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [50]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [51]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [55]:
frame2['debt'] = np.arange(6.)

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [57]:
val = pd.Series([-1.2, -1.5, -1.7], 
                index=['two', 'four', 'five'])

In [58]:
frame2['debt'] = val

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'

In [61]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [62]:
del(frame2['eastern'])

In [63]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2002: 3.6}}

In [66]:
frame3 = pd.DataFrame(pop)

In [67]:
frame3

Nevada  Ohio
2001     2.4   NaN
2002     2.9   3.6
2000     NaN   1.5

In [68]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     NaN   3.6   1.5

In [69]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   NaN
2002     2.9   3.6
2003     NaN   NaN

In [70]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [71]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   NaN     2.4
2002   3.6     2.9

In [72]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [73]:
frame3

state  Nevada  Ohio
year               
2001      2.4   NaN
2002      2.9   3.6
2000      NaN   1.5

In [75]:
# Possíveis entradas de dados para o construtor de DataFrame: pág 257

In [77]:
frame3.values

array([[2.4, nan],
       [2.9, 3.6],
       [nan, 1.5]])

In [78]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [80]:
# Objetos Index

In [81]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [82]:
index = obj.index

In [83]:
index

Index(['a', 'b', 'c'], dtype='object')

In [84]:
index[1:]

Index(['b', 'c'], dtype='object')

In [85]:
index[1] = 'd'

<class 'TypeError'>: Index does not support mutable operations

In [86]:
labels = pd.Index(np.arange(3))

In [87]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [88]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [89]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [90]:
frame3

state  Nevada  Ohio
year               
2001      2.4   NaN
2002      2.9   3.6
2000      NaN   1.5

In [91]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [92]:
'Ohio' in frame3.columns

True

In [93]:
2003 in frame3.index

False

In [94]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [95]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [96]:
# Alguns métodos e propriedades de Index: pág 261

In [97]:
# Funcionalidades Essenciais

In [98]:
# Reindexação

In [99]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], 
                index=['d', 'b', 'a', 'c'])

In [100]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [101]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [102]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [103]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], 
                 index=[0, 2, 4])

In [104]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [105]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [123]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [124]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [108]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [109]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [125]:
states = ['Texas', 'Utah', 'California']

In [116]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [126]:
frame.loc[['a', 'b', 'c', 'd'], states]

<class 'KeyError'>: "['b'] not in index"

In [118]:
# Argumentos da função reindex: pág 266